# Generated by Django 2.2.2 on 2019-07-04 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattribute',
            name='value',
        ),
        migrations.AddField(
            model_name='job',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='category_value',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='subcategory_value',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='UserBasicProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birthday', models.DateField()),
                ('ethnicity', models.CharField(max_length=250)),
                ('address_1', models.CharField(max_length=250)),
                ('address_2', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('zipcode', models.CharField(max_length=250)),
                ('education', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('years_experience', models.IntegerField()),
                ('relationship_status', models.CharField(max_length=250)),
                ('num_dependents', models.IntegerField()),
                ('sexual_orientation', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
