# Generated by Django 2.2.3 on 2019-07-12 19:38
from django.conf import settings
from django.db import migrations

with open(f'{settings.BASE_DIR}/seeds/001_roles_seed.sql','r') as seed:
    roles_seed = seed.read()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(roles_seed)

    ]

