# Generated by Django 2.2.2 on 2019-07-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190704_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
