# Generated by Django 2.2.3 on 2019-07-12 19:52
from django.conf import settings
from django.db import migrations

with open(f'{settings.BASE_DIR}/seeds/002_salary_seed.sql','r') as seed:
    sql_seed = seed.read()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190712_1938',),
    ]

    operations = [
        migrations.RunSQL(sql_seed)

    ]
