# Generated by Django 2.2.3 on 2019-07-12 20:02
from django.conf import settings
from django.db import migrations

with open(f'{settings.BASE_DIR}/seeds/000_questions_mappings_and_categories.sql','r') as seed:
    sql_seed = seed.read()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_salary_seed',),
    ]

    operations = [
        migrations.RunSQL(sql_seed)

    ]
