# Generated by Django 2.2.2 on 2019-07-04 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbasicprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userbasicprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
