# Generated by Django 2.2.3 on 2019-07-12 20:22
from django.conf import settings
from django.db import migrations

with open(f'{settings.BASE_DIR}/seeds/004_update_metrics.sql','r') as seed:
    sql_seed = seed.read()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_questions_and_metrics'),
    ]
    operations = [
        migrations.RunSQL(sql_seed)

    ]
