# Generated by Django 2.2.3 on 2019-07-08 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20190708_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswers',
            old_name='choice',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='userattribute',
            old_name='category_value',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='userattribute',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userattribute',
            name='subcategory_value',
        ),
        migrations.AddField(
            model_name='category',
            name='sir',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswers',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
