# Generated by Django 2.2.3 on 2019-07-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_update_user_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobattribute',
            name='attribute_name',
        ),
        migrations.RemoveField(
            model_name='jobattribute',
            name='attribute_value',
        ),
        migrations.AddField(
            model_name='jobattribute',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Subcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobattribute',
            name='value',
            field=models.FloatField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='questionmapping',
            name='ordinal_reverse',
            field=models.BooleanField(null=True),
        ),
    ]
