# Generated by Django 2.2.3 on 2019-07-12 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_update_job_attribute_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobanswer',
            name='user',
        ),
        migrations.AddField(
            model_name='jobanswer',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Job'),
            preserve_default=False,
        ),
    ]
