# Generated by Django 2.2.3 on 2019-07-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190708_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sir',
        ),
    ]
