# Generated by Django 2.2.3 on 2019-07-11 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190710_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='questionmapping',
            name='ordinal_reverse',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RoleSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=10)),
                ('minimum', models.FloatField()),
                ('average', models.FloatField()),
                ('maximum', models.FloatField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Role')),
            ],
        ),
    ]
