# Generated by Django 2.2.3 on 2019-07-08 21:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_remove_category_sir'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAnswers',
            new_name='UserAnswer',
        ),
    ]
