# Generated by Django 2.2.3 on 2019-07-13 23:48
from django.conf import settings
from django.db import migrations

with open(f'{settings.BASE_DIR}/seeds/003_ruca_scores_by_zipcode.sql','r') as seed:
    sql_seed = seed.read()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_more_job_attributes'),
    ]

    operations = [
        migrations.RunSQL(sql_seed)

    ]
