# Generated by Django 2.2.3 on 2019-07-11 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190711_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasicprofile',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Role'),
            preserve_default=False,
        ),
    ]
