# Generated by Django 2.2.3 on 2019-07-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_zipcode_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='score',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
