# Generated by Django 2.2.3 on 2019-07-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userbasicprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesalary',
            name='multiplier',
            field=models.FloatField(default=1.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolesalary',
            name='standardized_value',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
    ]
