# Generated by Django 2.2.3 on 2019-07-14 02:50
from django.conf import settings
from django.db import migrations

with open(f'{settings.BASE_DIR}/seeds/002_salary_seed.sql','r') as seed:
    sql_seed = seed.read()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_update_score_data_type'),
    ]

    operations = [
        migrations.RunSQL(sql_seed)

    ]
