# Generated by Django 2.2.3 on 2019-07-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190711_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolesalary',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='rolesalary',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolesalary',
            name='state',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
