# Generated by Django 2.2.3 on 2019-07-14 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_job_update_function'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbasicprofile',
            old_name='address_1',
            new_name='area_code',
        ),
        migrations.RenameField(
            model_name='userbasicprofile',
            old_name='address_2',
            new_name='pronouns',
        ),
        migrations.RemoveField(
            model_name='userbasicprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userbasicprofile',
            name='sexual_orientation',
        ),
        migrations.RemoveField(
            model_name='userbasicprofile',
            name='state',
        ),
        migrations.AlterField(
            model_name='jobanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.JobQuestion'),
        ),
    ]
