# Generated by Django 2.2.3 on 2019-07-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190712_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipcodeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5)),
                ('ruca_standardized', models.FloatField()),
                ('ruca_raw', models.FloatField()),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
