# Generated by Django 2.2.3 on 2019-07-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190714_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
