# Generated by Django 2.2.3 on 2019-07-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190715_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='address_2',
        ),
        migrations.AddField(
            model_name='userbasicprofile',
            name='city',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbasicprofile',
            name='state',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
