# Generated by Django 2.2.3 on 2019-07-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userattributeweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattribute',
            name='value',
            field=models.FloatField(max_length=250, null=True),
        ),
    ]
