# Generated by Django 2.2.3 on 2019-07-16 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_address_to_city_state'),
    ]

    operations = [
        migrations.RunSQL("""DELETE from api_choice where question_id = (select id from 
        api_question where question_text = 'One of these things is not like the other'
        and 
        input_type = 'image');

        delete FROM api_question where question_text = 'One of these things is not like the other'
        and 
        input_type = 'image';""")
    ]
