INSERT INTO api_role (role_name) VALUES ('software architect');
INSERT INTO api_role (role_name) VALUES ('copywriter');
INSERT INTO api_role (role_name) VALUES ('user interface designer');
INSERT INTO api_role (role_name) VALUES ('data quality manager');
INSERT INTO api_role (role_name) VALUES ('management information systems director');
INSERT INTO api_role (role_name) VALUES ('lead email specialist');
INSERT INTO api_role (role_name) VALUES ('it support manager');
INSERT INTO api_role (role_name) VALUES ('junior data engineer');
INSERT INTO api_role (role_name) VALUES ('email specialist');
INSERT INTO api_role (role_name) VALUES ('analytics manager');
INSERT INTO api_role (role_name) VALUES ('systems designer');
INSERT INTO api_role (role_name) VALUES ('javascript engineer');
INSERT INTO api_role (role_name) VALUES ('it technician');
INSERT INTO api_role (role_name) VALUES ('graphic art manager');
INSERT INTO api_role (role_name) VALUES ('senior data engineer');
INSERT INTO api_role (role_name) VALUES ('computer systems manager');
INSERT INTO api_role (role_name) VALUES ('business analyst');
INSERT INTO api_role (role_name) VALUES ('product manager');
INSERT INTO api_role (role_name) VALUES ('it director');
INSERT INTO api_role (role_name) VALUES ('application support analyst');
INSERT INTO api_role (role_name) VALUES ('lead database administrator');
INSERT INTO api_role (role_name) VALUES ('help desk technician');
INSERT INTO api_role (role_name) VALUES ('associate project manager');
INSERT INTO api_role (role_name) VALUES ('project manager');
INSERT INTO api_role (role_name) VALUES ('junior project manager');
INSERT INTO api_role (role_name) VALUES ('java developer');
INSERT INTO api_role (role_name) VALUES ('package designer');
INSERT INTO api_role (role_name) VALUES ('junior email specialist');
INSERT INTO api_role (role_name) VALUES ('user experience designer');
INSERT INTO api_role (role_name) VALUES ('javascript developer');
INSERT INTO api_role (role_name) VALUES ('applications engineer');
INSERT INTO api_role (role_name) VALUES ('customer support administrator');
INSERT INTO api_role (role_name) VALUES ('computer information research scientist');
INSERT INTO api_role (role_name) VALUES ('content strategist');
INSERT INTO api_role (role_name) VALUES ('associate data engineer');
INSERT INTO api_role (role_name) VALUES ('software developer');
INSERT INTO api_role (role_name) VALUES ('logo designer');
INSERT INTO api_role (role_name) VALUES ('lead visual designer');
INSERT INTO api_role (role_name) VALUES ('content developer');
INSERT INTO api_role (role_name) VALUES ('junior database administrator');
INSERT INTO api_role (role_name) VALUES ('developer');
INSERT INTO api_role (role_name) VALUES ('senior visual designer');
INSERT INTO api_role (role_name) VALUES ('computer programmer');
INSERT INTO api_role (role_name) VALUES ('associate dev ops engineer');
INSERT INTO api_role (role_name) VALUES ('customer support specialist');
INSERT INTO api_role (role_name) VALUES ('lead project manager');
INSERT INTO api_role (role_name) VALUES ('desktop support specialist');
INSERT INTO api_role (role_name) VALUES ('web designer');
INSERT INTO api_role (role_name) VALUES ('chief information officer (cio)');
INSERT INTO api_role (role_name) VALUES ('systems administrator');
INSERT INTO api_role (role_name) VALUES ('senior site reliability engineer');
INSERT INTO api_role (role_name) VALUES ('lead site reliability engineer');
INSERT INTO api_role (role_name) VALUES ('webmaster');
INSERT INTO api_role (role_name) VALUES ('customer service representative');
INSERT INTO api_role (role_name) VALUES ('network computer systems administrator');
INSERT INTO api_role (role_name) VALUES ('programmer');
INSERT INTO api_role (role_name) VALUES ('data analyst');
INSERT INTO api_role (role_name) VALUES ('editor');
INSERT INTO api_role (role_name) VALUES ('lead software engineer');
INSERT INTO api_role (role_name) VALUES ('it manager');
INSERT INTO api_role (role_name) VALUES ('senior email specialist');
INSERT INTO api_role (role_name) VALUES ('data architect');
INSERT INTO api_role (role_name) VALUES ('dev ops engineer');
INSERT INTO api_role (role_name) VALUES ('junior user experience designer');
INSERT INTO api_role (role_name) VALUES ('associate site reliability engineer');
INSERT INTO api_role (role_name) VALUES ('it analyst');
INSERT INTO api_role (role_name) VALUES ('technical support specialist');
INSERT INTO api_role (role_name) VALUES ('cloud system administrator');
INSERT INTO api_role (role_name) VALUES ('lead dev ops engineer');
INSERT INTO api_role (role_name) VALUES ('it systems administrator');
INSERT INTO api_role (role_name) VALUES ('junior visual designer');
INSERT INTO api_role (role_name) VALUES ('technical operations officer');
INSERT INTO api_role (role_name) VALUES ('systems architect');
INSERT INTO api_role (role_name) VALUES ('computer information systems manager');
INSERT INTO api_role (role_name) VALUES ('technical specialist');
INSERT INTO api_role (role_name) VALUES ('programmer analyst');
INSERT INTO api_role (role_name) VALUES ('broadcast designers');
INSERT INTO api_role (role_name) VALUES ('network architect');
INSERT INTO api_role (role_name) VALUES ('systems analyst');
INSERT INTO api_role (role_name) VALUES ('lead user experience designer');
INSERT INTO api_role (role_name) VALUES ('web application developer');
INSERT INTO api_role (role_name) VALUES ('art production manager');
INSERT INTO api_role (role_name) VALUES ('seo specialist');
INSERT INTO api_role (role_name) VALUES ('cloud services developer');
INSERT INTO api_role (role_name) VALUES ('system designer');
INSERT INTO api_role (role_name) VALUES ('user interface developer');
INSERT INTO api_role (role_name) VALUES ('visual image developer');
INSERT INTO api_role (role_name) VALUES ('multimedia developer');
INSERT INTO api_role (role_name) VALUES ('associate email specialist');
INSERT INTO api_role (role_name) VALUES ('technical support engineer');
INSERT INTO api_role (role_name) VALUES ('data engineer');
INSERT INTO api_role (role_name) VALUES ('front end developer');
INSERT INTO api_role (role_name) VALUES ('desktop support manager');
INSERT INTO api_role (role_name) VALUES ('brand identity developer');
INSERT INTO api_role (role_name) VALUES ('it coordinator');
INSERT INTO api_role (role_name) VALUES ('creative director');
INSERT INTO api_role (role_name) VALUES ('director of project management');
INSERT INTO api_role (role_name) VALUES ('security specialist');
INSERT INTO api_role (role_name) VALUES ('associate software engineer');
INSERT INTO api_role (role_name) VALUES ('information architect');
INSERT INTO api_role (role_name) VALUES ('associate visual designer');
INSERT INTO api_role (role_name) VALUES ('art director');
INSERT INTO api_role (role_name) VALUES ('network engineer');
INSERT INTO api_role (role_name) VALUES ('network administrator');
INSERT INTO api_role (role_name) VALUES ('support specialist');
INSERT INTO api_role (role_name) VALUES ('cloud systems engineer');
INSERT INTO api_role (role_name) VALUES ('it support specialist');
INSERT INTO api_role (role_name) VALUES ('back end developer');
INSERT INTO api_role (role_name) VALUES ('associate user experience designer');
INSERT INTO api_role (role_name) VALUES ('network systems administrator');
INSERT INTO api_role (role_name) VALUES ('design director');
INSERT INTO api_role (role_name) VALUES ('chief technology officer (cto)');
INSERT INTO api_role (role_name) VALUES ('junior dev ops engineer');
INSERT INTO api_role (role_name) VALUES ('senior database administrator');
INSERT INTO api_role (role_name) VALUES ('interaction designer');
INSERT INTO api_role (role_name) VALUES ('interface designer');
INSERT INTO api_role (role_name) VALUES ('senior user experience designer');
INSERT INTO api_role (role_name) VALUES ('writer');
INSERT INTO api_role (role_name) VALUES ('cloud product manager');
INSERT INTO api_role (role_name) VALUES ('cloud consultant');
INSERT INTO api_role (role_name) VALUES ('illustrator');
INSERT INTO api_role (role_name) VALUES ('software engineer');
INSERT INTO api_role (role_name) VALUES ('senior dev ops engineer');
INSERT INTO api_role (role_name) VALUES ('visual journalist');
INSERT INTO api_role (role_name) VALUES ('statistician');
INSERT INTO api_role (role_name) VALUES ('graphic designer');
INSERT INTO api_role (role_name) VALUES ('cloud architect');
INSERT INTO api_role (role_name) VALUES ('full stack developer');
INSERT INTO api_role (role_name) VALUES ('crm email specialist');
INSERT INTO api_role (role_name) VALUES ('visual designer');
INSERT INTO api_role (role_name) VALUES ('computer systems analyst');
INSERT INTO api_role (role_name) VALUES ('data center support specialist');
INSERT INTO api_role (role_name) VALUES ('associate database administrator');
INSERT INTO api_role (role_name) VALUES ('senior software engineer');
INSERT INTO api_role (role_name) VALUES ('lead data engineer');
INSERT INTO api_role (role_name) VALUES ('application developer');
INSERT INTO api_role (role_name) VALUES ('systems software engineer');
INSERT INTO api_role (role_name) VALUES ('software quality assurance analyst');
INSERT INTO api_role (role_name) VALUES ('system analyst');
INSERT INTO api_role (role_name) VALUES ('junior site reliability engineer');
INSERT INTO api_role (role_name) VALUES ('web developer');
INSERT INTO api_role (role_name) VALUES ('web administrator');
INSERT INTO api_role (role_name) VALUES ('help desk specialist');
INSERT INTO api_role (role_name) VALUES ('information security engineer');
INSERT INTO api_role (role_name) VALUES ('web programmer');
INSERT INTO api_role (role_name) VALUES ('junior software engineer');
INSERT INTO api_role (role_name) VALUES ('network system administrator');
INSERT INTO api_role (role_name) VALUES ('director of technology');
INSERT INTO api_role (role_name) VALUES ('layout artist');
INSERT INTO api_role (role_name) VALUES ('telecommunications specialist');
INSERT INTO api_role (role_name) VALUES ('computer network architect');
INSERT INTO api_role (role_name) VALUES ('senior project manager');
INSERT INTO api_role (role_name) VALUES ('database administrator');
